#!/bin/bash

# Temporary disable email confirmation for testing
echo "🔧 Temporary Email Confirmation Bypass"
echo "======================================"
echo ""

echo "If you're hitting rate limits and need to test immediately:"
echo ""
echo "1. TEMPORARILY DISABLE EMAIL CONFIRMATION:"
echo "   → Go to: Supabase → Authentication → Settings"
echo "   → Find: 'Enable email confirmations'"
echo "   → Turn it OFF temporarily"
echo "   → Save changes"
echo ""
echo "2. TEST YOUR APP:"
echo "   → Users can sign up without email confirmation"
echo "   → This lets you test other functionality"
echo ""
echo "3. RE-ENABLE LATER:"
echo "   → After rate limits reset (1 hour)"
echo "   → Turn email confirmations back ON"
echo "   → Test the email flow then"
echo ""
echo "⚠️  WARNING: Only use this for testing!"
echo "   Don't leave email confirmation disabled in production."
